# Generated by Django 6.0.4 on 2026-05-01 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVentaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ordenes', models.PositiveIntegerField(default=0)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto_mas_vendido', models.CharField(blank=True, max_length=150)),
                ('generado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reporte de venta diaria',
                'verbose_name_plural': 'Reportes de ventas diarias',
                'ordering': ['-fecha'],
            },
        ),
    ]
